### ISSUE TITLE
FatalThrowableError in channels.php line 14: Class 'Broadcast' not found

### ISSUE THREAD

**Issue by rtd62** [reliqarts/mardin#4]
So after I added the service provider in `app.php`, then I typed this into Terminal `php artisan vendor:publish --provider="ReliQArts\Mardin\MardinServiceProvider"`.

Unfortunately, terminal gave me another error:

```
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Class 'Broadcast' not found 
```

**Comment by reliq** [comment]
Hello @rtd62,

I am looking into this. 

Please check the Laravel log file to see additional details, including where this exception is being thrown from. 

Cheers 🍻

**Comment by rtd62** [comment]
All I had to do was clear my cache and run `php artisan optimize`. 🍻

**Comment by reliq** [comment]
Glad to see you managed to figure this out @rtd62. I myself couldn't reproduce the error. :beers:

**Comment by rtd62** [comment]
It was the environment I was running the Laravel instance in, it wasn't playing too nice lol
